export const CHANGE_FILTER_LIB = "CHANGE_FILTER_LIB";
export const CHANGE_FILTER_VALUE = "CHANGE_FILTER_VALUE";
export const TOGGLE_PREVIEW = "TOGGLE_PREVIEW";
export const DONE_FETCH_AUDIO = "DONE_FETCH_AUDIO";
